require 'dotenv/load'
require_relative 'activity'
require_relative 'activity_data'
require_relative 'activity_store'
require_relative 'hill'
require_relative 'hill_store'
require_relative 'strava_activity_downloader'
